# 使用方法 ansible-playbook -i hosts.ini start.yml
---
- hosts: gtm
  tags:
    - gtm
  tasks:
    - name: 启动 gtm
      shell: setsid gtm_ctl start -Z gtm -D {{ deploy_dir }}/data/gtm/ &


- hosts: gtm_proxy
  tags:
    - gtm_proxy
  tasks:
    - name: 启动 gtm_proxy
      shell: setsid gtm_ctl start -Z gtm_proxy -D {{ deploy_dir }}/data/gtm_proxy/ &


- hosts: datanode
  tags:
    - datanode
  tasks:
    - name: 启动 datanode
      shell: pg_ctl start -Z datanode -D {{ deploy_dir }}/data/datanode/


- hosts: coordinator
  tags:
    - coordinator
  tasks:
    - name: 启动 coordinator
      shell: pg_ctl start -Z coordinator -D {{ deploy_dir }}/data/coordinator/
